### ISSUE TITLE
Open source the SDK

### ISSUE THREAD

**Issue by guycreate** [gotenna/PublicSDK#10]
Is it possible to open source the actual frameworks used by the demo applications.  

I would like to develop macOS and linux applications but the iOS and Android are currently closed source and compiled to byte code.  

Even if certain features are proprietary such as the group encryption and command line interface over USB, it would be helpful to have the base message packet and BLE protocol OSS

**Comment by amit13091992** [comment]
have u accesed the demoapp?

**Comment by guycreate** [comment]
Yes.  Demoapp is good but the frameworks they used are closed source.  This makes it hard to port them to macOS and linux.   It is possible to decompile them but I am not sure where this stands with respect to the license and I'd rather have true open source for the SDK.    

Not sure why @gotenna is not responding to this question to even explain their position.

**Comment by amit13091992** [comment]
how did you set the application token for the device to connect to the applcation. plz help me i m stucked from 2 days in this only. @guycreate

**Comment by joshmakinda** [comment]
@guycreate for some reason we missed these notifications, sorry.
For the time being at least, the goTenna frameworks are not open source. 
Also, I am not in control of the decisions of whether the framework is made open or closed.

@amit13091992 is that error still happening for you? on Android only?

**Comment by amit13091992** [comment]
Yeah sir its coming for the sample code

**Comment by amit13091992** [comment]
Token is invalid its saying
Though i have registered to the gotenna website and it gave me the token
also
Bt everytime its saying: invalid token


I have tried with both android 5.0.1 and android 6.

**Comment by LEADNAV** [comment]
FYI Were still seeing the same token invalid on iOS. This was labeled and indentified as a bug in communications with your team over a few months ago.

DAMIAN CLAPPER
FOUNDER / CEO
LEADNAV SYSTEMS LLC
www.leadnavsystems.com<http://www.leadnavsystems.com/>
Damian@leadnavsystems.com<mailto:Damian@leadnavsystems.com>
1506 W Whispering Wind Dr Suite 120
Phoenix AZ 85085
Office 623-271-8088
Cell 757-374-2477

This email communication may contain CONFIDENTIAL INFORMATION WHICH ALSO MAY BE LEGALLY PRIVILEGED and is intended only for the use of the intended recipients identified above. If you are not the intended recipient of this communication, you are hereby notified that any unauthorized review, use, dissemination, distribution, downloading, or copying of this communication is strictly prohibited. If you are not the intended recipient and have received this communication in error, please immediately notify sender by reply email, delete the communication and destroy all copies. Thank you for your cooperation.

**Comment by amit13091992** [comment]
Thanx sir
Any help would be very helpfull sir😀.


If any update comes plz share that.

**Comment by joshmakinda** [comment]
Hmmm.
Ok,
Thanks for that.
@amit13091992 @LEADNAV 
Best thing to do is to send a quick message with all the information regarding this issue to support@gotenna.com.
Support team will sort out your issue as soon as possible, they'll be able to help you out and provide you the information you need on this.
