### ISSUE TITLE
In sample, method startBluetoothPairingIfPossible, why do you request location permission ?

### ISSUE THREAD

**Issue by ZeDvD** [gotenna/PublicSDK#16]
In the following code (PairingActivityjava->startBluetoothPairingIfPossible) : 

if (PermissionsManager.getInstance().hasLocationPermission())
                {
                    if (!willRememberGotenna)
                    {
                        // If we clear the last connected goTenna address,
                        // then the connection manager will look for any goTenna and try to connect to it.
                        // If we do not clear the address, it will specifically look for that last goTenna
                        // that it remembers being connected to.
                        gtConnectionManager.clearConnectedGotennaAddress();
                    }

                    gtConnectionManager.scanAndConnect();

I don't understand why you request location permission before connecting to the goTenna. We could connect without this permission.

Another question about gtConnectionManager.scanAndConnect() : if we didn't clear the previous address, this is always the same Gotenna that will be connected, event if there are 3 gotennas ON.  Right ?

**Comment by tcolligan-ap** [comment]
@ZeDvD For SDK 23 and above, in-order to use BLE scanning, the Location permission is required.

As for how `scanAndConnect`works, you are correct. The address is cached on disk, so if you do not clear it, the sdk will always try to connect to the same goTenna it paired with before, even if there are other goTenna devices on.
