### ISSUE TITLE
Does this SDK work with Mesh devices?

### ISSUE THREAD

**Issue by aaronblondeau** [gotenna/PublicSDK#19]
I have a pair of goTenna Mesh devices that I intended to use with this SDK.  However, both the iOS and Android sample apps fail to find either device.  I do see "Potenna" in the list of bluetooth devices.  The App Store goTenna app works just fine with them too.  Maybe I'm missing something?

**Comment by jperdomoz** [comment]
Hi Aaron, the SDK which can work with the new Mesh devices should be released in a couple of weeks. The current SDK is only for the V1 models, please stand by!

**Comment by aaronblondeau** [comment]
Thanks for the update.  Looking forward to the new SDK!
