### ISSUE TITLE
Can't pair with SDK on iOS 11

### ISSUE THREAD

**Issue by josh1093** [gotenna/PublicSDK#25]
Pairing with devices running iOS 11 doesn't seem to work.  You can see the issue with HelloGoTenna app (though I also see it in my own app).  The official GoTenna app does work on the same devices though. I have had success with devices running iOS 10.

**Comment by rahulsubu** [comment]
@josh1093 thank you for bringing this to our attention.
We are investigating this bug. Will keep you posted.

**Comment by josh1093** [comment]
Any word here?  I'm highly suspicious that I'm just missing some sort of new configuration option in iOS 11 that I'm not aware of.  This would be my apps first usage of bluetooth.  I tried again this morning with the most recent Xcode 9.0.1.

**Comment by rahulsubu** [comment]
@josh1093 we did find a bug that affects iOS 11 deployments. We have already fixed the issue. The SDK is going through QA and will be available on Github in the next couple of days.

**Comment by josh1093** [comment]
Great!

**Comment by imryan** [comment]
Resolved in 1724fb21a1a547942464116a248eecce1b83f200.
