### ISSUE TITLE
Does the GoTenna SDK include mobile analytics

### ISSUE THREAD

**Issue by josh1093** [gotenna/PublicSDK#26]
I've noticed that the prebuilt framework includes: 

mobileanalytics-2014-06-30.json

Does that mean the SDK is reporting back some sort of analytics?  If so, is it possible to turn it off?

**Comment by imryan** [comment]
What you're seeing is just part of the `AWSCore` library's `AWSMobileAnalytics`. We are not using/reading analytics with our SDK.
