### ISSUE TITLE
Suggestion: Add nullability attributes

### ISSUE THREAD

**Issue by kckd-geocaching** [gotenna/PublicSDK#3]
This is by no means a dealbreaker but it would be really nice if nullability attributes were added to the iOS framework. That would make interop with Swift much more convenient.

**Comment by imryan** [comment]
Resolved in Resolved in 1724fb21a1a547942464116a248eecce1b83f200.

**Comment by imryan** [comment]
@kckd-geocaching Will add more nullability attributes over time to other classes. `GTCommandCenter` contains these in the latest release.
