### ISSUE TITLE
Mesh bluetooth connection occasionally drops on Android

### ISSUE THREAD

**Issue by benhirashima** [gotenna/PublicSDK#31]
I am developing an app using the SDK on Android. My app runs as a foreground service and is designed to send and receive messages on a regular basis. The app can be running for hours at a time. I have noticed that the Bluetooth connection to the Mesh occasionally drops every 0.5 to 1.5 hours. The problem is highly repeatable. I have observed it using three different phones (Galaxy S8 on Android 7.x, Galaxy S6 on Android 7.x and Nexus 5 on Android 6.x) with two different Mesh units. The problem occurs on both the original firmware the Meshes shipped with, and the latest that I installed just yesterday. Some potential sources that I have ruled out:    

- Mesh battery is not low. I conducted my tests with fully charged Meshes, and their batteries were more than 50% charged when the problems occurred.
- My app is not being killed by the Android system. It continues to run, and I have programmed it to automatically reconnect to the Mesh, which sometimes fails.
- Mesh does not go out of BT range. In my tests, I placed the phone and Mesh on a table 6" apart and never moved them during the tests.

I have attached a logcat file that shows one of these disconnection events on the Galaxy S8.

[gotenna_disco.log](https://github.com/gotenna/PublicSDK/files/1452065/gotenna_disco.log)

Noteworthy events:

    12:20:40.119 - My app attempts to send a broadcast message
    12:20:47.220 - My app receives a timeout error code (-109)
    12:21:00.334 - My app attempts to send another broadcast message
    12:21:02.269 - GTEventNotifier: PERIPHERAL WRITE ERROR: ERROR WRITING PACKET - STATUS: 133
    12:21:02.300 - GTEventNotifier: CLOSING BLUETOOTH CONNECTION
    12:21:02.462 - GTEventNotifier: BLUETOOTH DISCONNECTED
    12:21:02.489 - My app receives a signal that the goTenna disconnected
    12:21:02.735 - My app starts scanning for the goTenna
    12:21:27.729 - My app gives up after 25 seconds of scanning without success

Note that before 12:20:40.119, the app had successfully sent 100+ broadcast messages over a period of about 30 minutes. This log just shows where things started to go sideways.

**Comment by rahulsubu** [comment]
@benhirashima we are aware of an issue with the Bluetooth chip from NXP that we use with goTenna Mesh. The version FW that NXP provides has a bug that forces the Bluetooth chip to reboot once every hour or so.
We are working with NXP to fix this. We hope to roll out an update shortly.

**Comment by benhirashima** [comment]
Great news! Looking forward to the update.

**Comment by ZeDvD** [comment]
Same issue for me. But it's not every hour it may e more often.

**Comment by ZeDvD** [comment]
Any news about the fix on this issue ?

Below, some logs from my app. Is it the same issue ?

12-16 18:23:34.421 16800-16800/fr.myapp D/GOTENNA_MSG: sendMessage
12-16 18:23:34.441 16800-18884/fr.myapp D/EncryptionCounterMan: Saved EncryptionCounters to disk: true
12-16 18:23:34.471 16800-16800/fr.myapp I/GTEventNotifier: COMMAND 126 STARTING: SENDING MESSAGE TO: 92160620209264 
12-16 18:23:41.471 16800-16800/fr.myapp I/GTEventNotifier: COMMAND TIMEOUT ON 126, SEND MESSAGE (RECEIVER:92160620209264)
12-16 18:23:51.901 16800-16800/fr.myapp D/GOTENNA_MSG: sendMessage
12-16 18:23:51.911 16800-18969/fr.myapp D/EncryptionCounterMan: Saved EncryptionCounters to disk: true
12-16 18:23:51.931 16800-16800/fr.myapp I/GTEventNotifier: COMMAND 127 STARTING: SENDING MESSAGE TO: 92160620209264 
12-16 18:23:55.961 16800-17050/fr.myapp I/GTEventNotifier: PERIPHERAL WRITE ERROR: ERROR WRITING PACKET - STATUS: 133
12-16 18:23:55.961 16800-17050/fr.myapp D/BluetoothGatt: close()
12-16 18:23:55.961 16800-17050/fr.myapp D/BluetoothGatt: unregisterApp() - mClientIf=8
12-16 18:23:55.961 16800-17050/fr.myapp I/GTEventNotifier: CLOSING BLUETOOTH CONNECTION
12-16 18:23:55.971 16800-16980/fr.myapp D/BluetoothGatt: onClientConnectionState() - status=8 clientIf=8 device=CE:96:5B:35:16:34
12-16 18:23:55.981 16800-16800/fr.myapp I/GTEventNotifier: REINSERTING INCOMPLETE COMMAND: SEND MESSAGE (RECEIVER:92160620209264) TO FRONT OF QUEUE.
12-16 18:23:55.981 16800-16980/fr.myapp W/BluetoothGatt: Unhandled exception in callback
                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.BluetoothGattCallback.onConnectionStateChange(android.bluetooth.BluetoothGatt, int, int)' on a null object reference
                                                                            at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:228)
                                                                            at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:70)
                                                                            at android.os.Binder.execTransact(Binder.java:453)
12-16 18:23:55.991 16800-16800/fr.myapp I/GTEventNotifier: INITIATING SCAN FOR GOTENNA: CE:96:5B:35:16:34
12-16 18:23:55.991 16800-16800/fr.myapp D/BluetoothAdapter: STATE_ON
12-16 18:23:55.991 16800-16800/fr.myapp D/BluetoothAdapter: STATE_ON
12-16 18:23:55.991 16800-16800/fr.myapp D/BluetoothAdapter: STATE_ON
12-16 18:23:56.001 16800-16800/fr.myapp D/BluetoothAdapter: STATE_ON
12-16 18:23:56.001 16800-16800/fr.myapp D/BluetoothLeScanner: could not find callback wrapper
12-16 18:23:56.001 16800-16800/fr.myapp D/BluetoothAdapter: STATE_ON
12-16 18:23:56.001 16800-16800/fr.myapp D/BluetoothAdapter: STATE_ON
12-16 18:23:56.001 16800-16800/fr.myapp D/BluetoothLeScanner: Start Scan
12-16 18:23:56.001 16800-16800/fr.myapp D/BluetoothAdapter: STATE_ON
12-16 18:23:56.001 16800-16800/fr.myapp D/BluetoothAdapter: STATE_ON
12-16 18:23:56.001 16800-16800/fr.myapp D/BluetoothAdapter: STATE_ON
12-16 18:23:56.001 16800-16800/fr.myapp D/BluetoothAdapter: STATE_ON
12-16 18:23:56.051 16800-17009/fr.myapp D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=8
12-16 18:23:56.051 4248-4420/? E/BtGatt.GattService: [GSIM LOG]: gsimLogHandler: fr.myapp, msg: MESSAGE_START_SCAN
12-16 18:23:56.061 16800-16800/fr.myapp I/GTEventNotifier: BLUETOOTH DISCONNECTED
12-16 18:23:56.061 16800-16800/fr.myapp D/GOTENNA_CONNECT: CONNECTION STATE UPDATED
12-16 18:23:56.061 16800-16800/fr.myapp D/GOTENNA: DISCONNECTED
12-16 18:23:56.061 16800-16800/fr.myapp D/receiveGotennaState: 61
12-16 18:23:56.071 16800-16800/fr.myapp D/GOTENNA_CONNECT: CONNECTION STATE UPDATED
12-16 18:23:56.071 16800-16800/fr.myapp D/GOTENNA: SCANNING
12-16 18:23:56.071 16800-16800/fr.myapp D/receiveGotennaState: 61
12-16 18:23:56.111 16800-16812/fr.myapp D/ScanRecord: parseFromBytes
12-16 18:23:56.111 16800-16800/fr.myapp I/GTEventNotifier: FOUND GOTENNA, ATTEMPTING TO CONNECT: CE:96:5B:35:16:34
12-16 18:23:56.111 16800-16800/fr.myapp D/BluetoothAdapter: STATE_ON
12-16 18:23:56.111 16800-16800/fr.myapp D/BluetoothAdapter: STATE_ON
12-16 18:23:56.111 16800-16800/fr.myapp D/BluetoothAdapter: STATE_ON

**Comment by tcolligan-ap** [comment]
@ZeDvD Yes, it appears to be the same issue. From what we have seen `PERIPHERAL WRITE ERROR: ERROR WRITING PACKET - STATUS: 133` typically indicates that the BT Disconnect issue has occurred. We have made good progress on fixing the issue, but I don't have a specific ETA for you right now as to when you might see an update for the fix. Will keep this thread updated as things progress.

**Comment by ZeDvD** [comment]
May be also an exception cach to add in the SDK : it appears during group creation process, when the smartphone receives the group invitation sent by another one

W/BluetoothGatt: Unhandled exception in callback
                 java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                     at com.gotenna.sdk.responses.GTResponse.<init>(SourceFile:92)
                     at com.gotenna.sdk.commands.GTCommandCenter.dispatchResponse(SourceFile:855)
                     at com.gotenna.sdk.responses.ChunkProcessor.registerIncomingReadChunk(SourceFile:61)
                     at com.gotenna.sdk.bluetooth.GTPeripheralHandler$4.onCharacteristicChanged(SourceFile:567)
                     at android.bluetooth.BluetoothGatt$1.onNotify(BluetoothGatt.java:485)
                     at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:399)
                     at android.os.Binder.execTransact(Binder.java:453)
I/GTEventNotifier: COMMAND 162 STARTING: SENDING GET MESSAGE
W/BluetoothGatt: Unhandled exception in callback
                 java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                     at com.gotenna.sdk.responses.GTResponse.<init>(SourceFile:92)
                     at com.gotenna.sdk.commands.GTCommandCenter.dispatchResponse(SourceFile:855)
                     at com.gotenna.sdk.responses.ChunkProcessor.registerIncomingReadChunk(SourceFile:61)
                     at com.gotenna.sdk.bluetooth.GTPeripheralHandler$4.onCharacteristicChanged(SourceFile:567)
                     at android.bluetooth.BluetoothGatt$1.onNotify(BluetoothGatt.java:485)
                     at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:399)
                     at android.os.Binder.execTransact(Binder.java:453)

**Comment by ZeDvD** [comment]
Do you have any news about this bug ? When the bluetooth disconnect the antenna, it is not possible to reconnect it : you must shutdown the antenna then restart it. It's a real problem for my customer : the antenna is not necessarly easily accessible, it may be in a pocket so it's a real frustration each time you have to shutdown it

**Comment by rahulsubu** [comment]
@ZeDvD we will be rolling out an over the air FW fix for this BT disconnect issue in the coming months. Stay tuned for more updates on this.

**Comment by benhirashima** [comment]
What's the status on this? It was been **way** too long without a fix. I have suspended development of my app, and will not begin work on an iOS version until this bug is fixed. It is **killing** the user experience. I feel bad that I told people to go buy a goTenna Mesh when it has this fatal flaw. Please tell me all that work I put into my app wasn't for nothing.

**Comment by tcolligan-ap** [comment]
@benhirashima We just released a 5.0 version of the mesh application yesterday. It contains a number of changes and fixes that we have been working on for a while. The application will apply a firmware update that will fix the Bluetooth reboot issue that has been plaguing us for the past few months.

If you could please download the latest version of the app, apply the firmware update to your devices and let us know if that improves the Bluetooth experience, we would greatly appreciate it!

We are currently working on rolling out a number of these changes to the SDK as well, but that is still in the works.

With the new updated firmware, you should seen an improvement even when using the current sdk with your own application.

**Comment by bhirashi** [comment]
@tcolligan-ap I tried it, but got a firmware update error. I started the update process, walked away for a bit, came back and the light on the goTenna Mesh was blinking continuously. The goTenna app displayed a firmware update error notification. I tried to connect to the goTenna Mesh, but no luck. I killed the app and restarted it. It then prompted me to send a crash report, which I did. I power cycled the goTenna Mesh and tried to connect to it, and again no luck. I unpaired it and tried to pair it again, but no luck. The app didn't find it. I hope it's not bricked. Please advise.

**Comment by bhirashi** [comment]
BTW, yes I was using version 5.0 of the goTenna app. The phone is a Galaxy S8 on Android 8.0.

**Comment by tcolligan-ap** [comment]
@bhirashi That does sound like a potential issue where the unit may have been bricked. If you can, please shoot an email to virginia@gotenna.com with any additional details you can provide. Worst case, if it is bricked, we will ship you new fully updated units to replace the ones that no longer work. Thanks.

**Comment by bhirashi** [comment]
@tcolligan-ap I have three other Meshes. If you'll replace the bricked ones, I'd be willing to try again on another one. Is there any special procedure you'd like me to try? Any way to obtain a firmware log or something?

**Comment by tcolligan-ap** [comment]
@bhirashi If you reach out to virginia@gotenna.com and let her know your current situation, she can help you out with some troubleshooting steps for updating the other units, as well as discuss replacing any potentially broken units.

**Comment by dsuresh-ap** [comment]
Please contact support if the issue persists.
