### ISSUE TITLE
sendBroadcastMessage() suddenly times out and stops working on Android

### ISSUE THREAD

**Issue by benhirashima** [gotenna/PublicSDK#32]
This is a problem I have observed on a Galaxy S8 on Android 7.x with the latest goTenna Mesh firmware. This happened after successfully sending hundreds of shouts over a two hour period. I suddenly started getting `COMMAND_TIME_OUT_ERROR_CODE(-109)` from `sendBroadcastMessage()`. Once I got the error, I got the error on every subsequent call to `sendBroadcastMessage()` after that and it didn't stop happening even after 20 minutes. I never got a signal from `GTConnectionListener` that the Mesh disconnected. The Mesh was still on, with >80% battery and the light was not blinking like it does when it's disconnected. The Mesh and phone were about 3 feet away from each other with clear line of sight, and were never moved. The setup worked fine for 2 hours, and nothing had changed when I suddenly started getting the `COMMAND_TIME_OUT_ERROR_CODE` error. Unfortunately, I was not able to capture the full logcat output for this event. I only have the log my app itself keeps.

**Comment by rahulsubu** [comment]
@benhirashima have you been able to reproduce this issue?

**Comment by benhirashima** [comment]
I have only seen this once. It's a bit time consuming to reproduce, but I will try and will make sure to get the full logcat output when it happens.

**Comment by rahulsubu** [comment]
@benhirashima sounds good!

**Comment by rahulsubu** [comment]
@benhirashima what app are you building using this SDK?

**Comment by dsuresh-ap** [comment]
Closing this issue for now. Please file a new issue if this re-occurs.
