### ISSUE TITLE
goTenna Mesh does not support Shout

### ISSUE THREAD

**Issue by dferg7** [gotenna/PublicSDK#34]
I read on the https://www.gotenna.com/pages/faqs-gotenna-mesh page that the goTenna Mesh does not support broadcast/shout messages. Will the SDK ever be updated to support meshing with broadcasting? My current app only uses broadcast messaging because only users with the app token used from my app will receive the messages anyway. Otherwise, I will have to do a big re-write to figure out the group and 1-1 messaging in order to enable the meshing technology.

**Comment by dferg7** [comment]
Also to add on to that, I saw in the SDK that the mesh only supports up to 3 "hops" is this statement correct?

**Comment by tcolligan-ap** [comment]
@dferg7 The mesh device does support broadcast/shouts. However it does not currently support hopping in shouts. So you can still use shouts just like you did with the V1 goTenna, as a point to point communication.

We will be adding in hopping to shouts early next year, but there is no specific ETA on that feature right now.

As for the 3 hops statement, yes that is correct. We currently only support up to 3 hops at the moment, but there are plans to increase that in the future as well!
