### ISSUE TITLE
Should the official goTenna app be receiving our tokenized messages? (it is)

### ISSUE THREAD

**Issue by jeffjvick** [gotenna/PublicSDK#39]
I have noticed that the official goTenna app can send/receive both shout and 1:1 messages from the HelloGoTenna app with a developer token set.  

I was under the impression the purpose of the token was to prevent different apps from messaging each other but this doesn't seem to be the case with the official goTenna app.  I can send a 1:1 message from the tokenized HelloGoTenna app to it and have it send a message back just find.

Is there something special about the official app that it can see everything or is this a bug?

I haven't been able to test yet if the tokens work even for developer apps because I'm still waiting to receive another SDK token.  It's possible the tokenizing is just broken in general (or I'm misinterpreting how it is use).

**Comment by jeffjvick** [comment]
Thanks, looking forward to testing out the fix with another token to confirm the apps are segregated.

**Comment by tcolligan-ap** [comment]
@jeffjvick The webpage should be fixed, and will distribute more SDK tokens now https://www.gotenna.com/pages/sdk

**Comment by jeffjvick** [comment]
@tcolligan-ap Thanks, I actually picked up one yesterday.  Confirmed the bug about apps with different tokens being able to talk to each other (in addition to the official app).  I will wait for the SDK update to test again that this is fixed.

**Comment by dsuresh-ap** [comment]
Pro SDK for Android has been released. iOS is still in beta and will follow shortly. Please verify if the issue still exists and create a new issue if it still does.
