### ISSUE TITLE
SDK support for anything but Android or IOS?

### ISSUE THREAD

**Issue by ThreeSixes** [gotenna/PublicSDK#40]
I realize this is a duplicate question but I wanted to give this a bump - is there still a plan for a USB and/or Raspberry Pi/BTLE version of the SDK? Making bridges from Gotenna Meshes and Android/IOS devices is prohibitively expensive and needlessly complex. Do you guys have an ETA on the release of the SDKs promised last year?

**Comment by dsuresh-ap** [comment]
Python SDK is now released.
