### ISSUE TITLE
SDK for Gotenna Pro

### ISSUE THREAD

**Issue by ZeDvD** [gotenna/PublicSDK#41]
I just received my Gotenna PRO, but I don't see any update of the SDK to program them. When will you update the SDK to address PRO ?

**Comment by Petefish88** [comment]
push

**Comment by ZeDvD** [comment]
Can you please give us a delvery date for SDK Gotenna  PRO  ?

**Comment by tcolligan-ap** [comment]
@ZeDvD Hi, unfortunately I cannot give you an exact delivery date for the Pro SDK. We have been very busy with a lot of different projects here at goTenna! I can tell you that we are working on the Pro SDK right now, and trying our best to make sure it works well before we hand it out! Our rough estimate right now puts the delivery date sometime in October. Will keep you updated! Thanks.

**Comment by ZeDvD** [comment]
Hi
We are near the end of october. Can you give us a real delivery date for the PRO sdk ?
Regards

**Comment by dsuresh-ap** [comment]
Pro SDK for Android has been released. iOS is still in beta and will follow shortly.
