### ISSUE TITLE
Publish the Javadocs!

### ISSUE THREAD

**Issue by loisaidasam** [gotenna/PublicSDK#43]
I see them in the repo, but I don't know if they're published anywhere.

Doing this is as simple as going to the github project's settings page:

https://github.com/gotenna/PublicSDK/settings

and under `GitHub Pages` choosing `master branch` and clicking `Save`

Voila:

https://loisaidasam.github.io/PublicSDK/android-public-sdk/javadocs/

**Comment by tcolligan-ap** [comment]
@loisaidasam Great idea, it is done, docs can now be found [here](https://gotenna.github.io/PublicSDK/ios-public-sdk/GoTennaSDKDocs/html/) and [here](https://gotenna.github.io/PublicSDK/android-public-sdk/javadocs/). Thanks!

**Comment by loisaidasam** [comment]
🙌
