### ISSUE TITLE
iOS Add method to permanently disconnect

### ISSUE THREAD

**Issue by tcolligan-ap** [gotenna/PublicSDK#7]
Calling `[[GTPairingManager shared] stopScanningConnect];` will cause the goTenna to disconnect but the the SDK will immediately start scanning again for a new goTenna to connect to.

Need to expose a method that allows people to disconnect that will not start the BLE scanning process again.

**Comment by imryan** [comment]
Implemented in the latest SDK release. See `GTPairingConnectionState`'s `GTConnectionState` enum.
