### ISSUE TITLE
Context in EmergencyManager

### ISSUE THREAD

**Issue by radarku** [gotenna/PublicSDK#9]
Just to make sure... are you using the Context that I pass in to GoTenna.setApplicationToken() for the resource lookup in the following function call:

com.gotenna.sdk.commands.GTStoreDateTimeEmergencyManager.getEmergencyMessage(SourceFile:120)

Thanks!

**Comment by tcolligan-ap** [comment]
@radarku Yes, `context.getApplicationContext();` is called on the context passed into `setApplicationToken()` and it is used in various spots throughout the SDK. Are you encountering an issue?

**Comment by radarku** [comment]
Yes, but it's more likely my mistake than yours.  Thanks.
